### ISSUE TITLE
close the menu programmatically

### ISSUE THREAD

**Issue by jacquesgiraudel** [HeyAlex/CornerSheet#1]
Is there away to close the menu programmatically ?

Thanks

**Comment by HeyAlex** [comment]
Hi. You can easily close menu by setting collapsed state to behavior. The same thing done in sample app, you can check [here](                    https://github.com/HeyAlex/CornerSheet/blob/84ffbe7d75c117ff8eaa96dec564d2498f7045af/app/src/main/java/com/github/heyalex/cornerdrawer/example/support/SupportFragment.kt#L38).

**Comment by HeyAlex** [comment]
Feel free to reopen if something unclear
