### ISSUE TITLE
Wrong Dependency name in 

### ISSUE THREAD

**Issue by Jasjot784** [HeyAlex/CornerSheet#2]
@HeyAlex  at the end of your readme you have mentioned this
 [
dependencies {

    //only CornerSheetBehavior
    implementation 'com.github.HeyAlex.CornerSheet:core:v1.0.1'

    //CornerSheetBehavior and CornerDrawer
    implementation 'com.github.HeyAlex.CornerSheet:drawer:v1.0.1'
}
] This doesnt work until all alphabets are lower case.

**Comment by Jasjot784** [comment]
@Jasjot784 @HeyAlex  the correct implementation is

dependencies {

    //only CornerSheetBehavior
    implementation 'com.github.heyalex.cornersheet:core:v1.0.1'

    //CornerSheetBehavior and CornerDrawer
    implementation 'com.github.heyalex.cornersheet:drawer:v1.0.1'
}

**Comment by HeyAlex** [comment]
Thanks for noticing that.
